import Head from 'next/head'
import Appbar from '../components/system/Appbar'
import Background from '../components/system/Background'
import Content from '../components/system/Content'
import Controls from '../components/system/Controls'

export default function Home() {
  return (
    <>
      <Head>
        <title>Time Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background />
      <Appbar />
      <Content />
      <Controls />
    </>
  )
}
